### ISSUE TITLE
1.19.0 support

### ISSUE THREAD

**Issue by EdgarMontelongo** [Victorsueca/FrameXAct#4]

**Comment by Victorsueca** [comment]
Minecraft version 1.19 and 1.19.1 both contain vulnerabilities (especially the later one) that where patched over the course of time. As far as I know, Mojang currently only supports the latest release in the 1.19.x series (1.19.2 at the time of writing), as that is the only version that is up to date with security fixes.
Thus, I will be following suit and not supporting 1.19.0 either.
